name: LyaimTech backend

on: 
    push: 
        branches: [ main ]

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code backend
              uses: actions/checkout@v3
            
            - name: Docker Login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push
              uses: docker/build-push-action@v5 
              with:
                context: ./backend
                file: ./backend/Dockerfile
                push: true
                tags: |
                  rohitsamasi555/lyaim-tech-backend:${{ github.sha }} 
                  rohitsamasi555/lyaim-tech-backend:latest
            
            - name: Deploy to VM
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: "44.214.177.203" 
                username: "ubuntu" 
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script: |
                  sudo docker pull rohitsamasi555/lyaim-tech-backend:latest

                  if sudo docker ps -a --format '{{.Names}}' | grep -q "^lyaim-backend$"; 
                  then
                   sudo docker stop lyaim-backend
                   sudo docker rm lyaim-backend
                  fi

                  sudo docker run -d \
                    --name lyaim-backend \
                    -e PORT=9000 \
                    -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
                    -e NODE_ENV=development \
                    -e PAYPAL_MODE="${{ secrets.PAYPAL_MODE }}" \
                    -e PAYPAL_CLIENT_ID="${{ secrets.PAYPAL_CLIENT_ID }}" \
                    -e PAYPAL_CLIENT_SECRET="${{ secrets.PAYPAL_CLIENT_SECRET }}" \
                    -e MONGO_URL="${{ secrets.MONGO_URL }}" \
                    -p 9000:9000 \
                    --restart always \
                    rohitsamasi555/lyaim-tech-backend:latest

                   sudo docker image prune -f
